### ISSUE TITLE
Use Ordering in BinSearch over Bool

### ISSUE THREAD

**Issue by BlackCapCoder** [meooow25/haccepted#43] opened 2022-11-17 08:35 UTC
Why not use `Ordering` here rather than `Bool`?
https://github.com/meooow25/haccepted/blob/d7313e905988a5d1ef0f4666aa2b91169d48f26f/src/BinSearch.hs#L33-L39

Anyways, a very elegant way to do this is to traverse a lazy search tree!
```haskell
data Bin a = Tip a | Bin a (Bin a) (Bin a)


bsearch ∷ (a → Ordering) → Bin a → a
bsearch f = go where
  go = \case
    Tip a → a
    Bin a l r →
      case f a of
        LT → go l
        GT → go r
        EQ → a

-- Starting with 0, grow exponentially until the
-- left branch is taken, then grow a perfectly balanced
-- binary tree between the extremes
--
ascend = Bin 1 (Tip 0) (go 2) where
  go n | x ← n+n =
    Bin x (interval (succ n) (pred x)) (go x)

interval lo hi =
  case size of
    0 → Tip lo
    1 → Bin lo  (Tip lo) (Tip hi)
    _ → Bin mid (interval lo (pred mid)) (interval (succ mid) hi)
  where
    size = hi - lo
    mid  = lo + div size 2
```

Here are some usecases:
```haskell
-- O(log n). Integer square root
--
isqrt n =
  bsearch (compare n . join (*)) ascend
```

```haskell
-- Farey algorithm to approximate rational numbers
farey lim x = go lim $ fareyGrow (floor x % 1) (ceiling x % 1)
  where
    go 0 (Bin f _ _) = f
    go n (Bin f l r)
      | toRational f == x = f
      | toRational f <  x = go (n-1) r
      | let               = go (n-1) l

fareyGrow =
  grow \bot top
    -> (numerator bot   + numerator top)
     % (denominator bot + denominator top)

-- Grow a tree using a splitter
grow split lo hi
  = Bin mid (grow split lo mid) (grow split mid hi)
  where
    mid = split lo hi
```

**Comment by meooow25** [comment] 2022-11-18 16:42
> Why not use `Ordering` here rather than `Bool`?

Because `Bool` is enough to perform a binary search. `Ordering` only sometimes allows exiting the search early on `EQ`.

> Anyways, a very elegant way to do this is to traverse a lazy search tree!

That's an interesting suggestion. As far as I can see, the main benefit of this is increased flexibility because we are free to build the tree however we want. Choosing the split strategy or building a non-integral tree can't be done with the current code. However, I don't see a use case for this in competitive programming. Have you seen some problems where this is useful? Note that unbounded search (`ascend`), can be easily be done with the current implementation too.

```hs
-- Binary search with only a start index
binSearchUnbounded :: Integral i => (i -> Bool) -> i -> i
binSearchUnbounded f = go 1 where
    go d i
        | f i       = binSearch f (i - d + 1) (i - 1)
        | otherwise = go (2 * d) (i + 2 * d)
```

Now let's talk about what's wrong.  
First, you have a bug, 2 does not exist in your `ascend` tree. This is easy to fix.  
Second, your `isqrt` sometimes returns $\lfloor \sqrt x \rfloor$ and sometimes $\lceil \sqrt x \rceil$, which is not great. This is harder to fix, try it.  
I have not inspected the Farey function.

The tree approach is also more verbose. Which is a price to pay for flexibility perhaps.  
But it's also much slower (~4-7x for `Int`s depending on whether the tree is shared), which is a deal breaker. Benchmarks [here](https://gist.github.com/meooow25/6a75d2e04ba1a425895421bf4db25460). From what I can see this is primarily because GHC is able to unbox all the `Ints` in the current implementation, which it cannot do with a tree.

Overall, I am not inclined to add this.

**Comment by BlackCapCoder** [comment] 2022-11-18 19:01
Thank you for the elaborate response! I'll look into the performance problem, but for now, I'm pretty sure `isqrt` can be fixed like this?

```haskell
isqrt' n | x <- isqrt n = if x*x > n then pred x else x
```

**Comment by BlackCapCoder** [comment] 2022-11-18 21:33
If I [manually unbox the numbers](https://gist.github.com/BlackCapCoder/e09a026be33321712dca65976d53adbe), I beat your version by a landslide:

```
All
  isqrt0: OK (2.46s)
    813  ms ±  44 ms
  isqrt:  OK (0.57s)
    78.2 ms ± 2.6 ms
```

**Comment by BlackCapCoder** [comment] 2022-11-18 22:18
And here's your version unboxed, about twice as fast as mine:

```haskell
binSearch1 f = go where
  go l h
    | 1# ← l ># h = I# l
    | f (I# m)    = go l (m -# 1#)
    | otherwise   = go (m +# 1#) h
    where m = (l +# h) `iShiftRL#` 1#

binSearchUnbounded1 f (I# i0) = go 1# i0 where
  go d i
    | f (I# i)  = binSearch1 f (i -# d +# 1#) (i -# 1#)
    | otherwise = go (2# *# d) (i +# 2# *# d)

isqrt1 n =
  binSearchUnbounded1 ((>n) . join (*)) 0 - 1
```

```
  isqrt0: OK (2.46s)                                                                                                                  
    813  ms ±  59 ms                                                                                                                  
  isqrt1: OK (0.26s)                                                                                                                  
    36.2 ms ± 1.4 ms                                                                                                                  
  isqrt:  OK (0.59s)                                                                                                                  
    81.4 ms ± 3.3 ms
```

**Comment by meooow25** [comment] 2022-11-18 23:49
> I'm pretty sure `isqrt` can be fixed like this?

That's fixing it after the fact, which is an option sure, but it becomes one more thing to add on top of the search.

> Here are two more functions to motivate the design:

`natsLevelOrder` and `natsBinaryOrder` are not binary search trees so I don't see how this is relevant.

> If I manually unbox the numbers, I beat your version by a landslide:
> And here's your version unboxed, about twice as fast as mine:
> ...

You may be benchmarking with optimizations off. GHC does this is kind of unboxing well by itself.

I'll summarize my views on this issue:
- I'm open to adding binary searching via a `Bin` tree if there are competitive programming problems where this is useful. I can't think of any, so if you could share some that would be great.
- Binary searching via `Bin` is definitely not replacing the existing `binSearch` because it is much slower.

**Comment by BlackCapCoder** [comment] 2022-11-19 00:07
`natsBinaryOrder` can be viewed as a perfectly balanced binary tree, so you can use it to create other searches by for instance `fmap`ping some function over it

**Comment by BlackCapCoder** [comment] 2022-11-19 00:48
```
natsLevelOrder
        ┌────────1──────────┐
        │                   │
   ┌───2┴────┐         ┌───3┴────┐
   │         │         │         │
 ┌─4─┐    ┌─5┴─┐    ┌─6┴─┐    ┌─7┴─┐
 │   │    │    │    │    │    │    │
┌8┐ ┌9┐ ┌10┐ ┌11┐ ┌12┐ ┌13┐ ┌14┐ ┌15┐
│ │ │ │ │  │ │  │ │  │ │  │ │  │ │  │
╵ ╵ ╵ ╵ ╵  ╵ ╵  ╵ ╵  ╵ ╵  ╵ ╵  ╵ ╵  ╵

natsBinaryOrder
         ┌────────1─────────┐
         │                  │
    ┌───2┴────┐        ┌───3┴────┐
    │         │        │         │
 ┌─4┴─┐    ┌─6┴─┐   ┌─5┴─┐    ┌─7┴─┐
 │    │    │    │   │    │    │    │
┌8┐ ┌12┐ ┌10┐ ┌14┐ ┌9┐ ┌13┐ ┌11┐ ┌15┐
│ │ │  │ │  │ │  │ │ │ │  │ │  │ │  │
╵ ╵ ╵  ╵ ╵  ╵ ╵  ╵ ╵ ╵ ╵  ╵ ╵  ╵ ╵  ╵

interval 1 15
       ┌───────8──────────┐
       │                  │
   ┌───4───┐        ┌────12─────┐
   │       │        │           │
 ┌─2─┐   ┌─6─┐   ┌─10──┐     ┌─14──┐
 │   │   │   │   │     │     │     │
┌1┐ ┌3┐ ┌5┐ ┌7┐ ┌9┐  ┌11┐  ┌13┐  ┌15┐
│ │ │ │ │ │ │ │ │ │  │  │  │  │  │  │
╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵  ╵  ╵  ╵  ╵  ╵  ╵

interval' 1 15
               ┌───────────────8──────────────────────┐
               │                                      │
       ┌───────4───────┐                  ┌─────────12┴──────────┐
       │               │                  │                      │
   ┌───2───┐       ┌───6───┐        ┌───10┴────┐           ┌────14─────┐
   │       │       │       │        │          │           │           │
 ┌─1─┐   ┌─3─┐   ┌─5─┐   ┌─7─┐   ┌─9┴─┐     ┌─11──┐     ┌─13──┐     ┌─15──┐
 │   │   │   │   │   │   │   │   │    │     │     │     │     │     │     │
┌1┐ ┌2┐ ┌3┐ ┌4┐ ┌5┐ ┌6┐ ┌7┐ ┌8┐ ┌9┐ ┌10┐  ┌11┐  ┌12┐  ┌13┐  ┌14┐  ┌15┐  ┌16┐
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │  │  │  │  │  │  │  │  │  │  │  │  │  │
╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵ ╵  ╵  ╵  ╵  ╵  ╵  ╵  ╵  ╵  ╵  ╵  ╵  ╵  ╵
```

**Comment by BlackCapCoder** [comment] 2022-11-19 02:47
> Because Bool is enough to perform a binary search. Ordering only sometimes allows exiting the search early on EQ.
This is very apparently from the difference in our tree's above. Your version has to walk all the way to the bottom of the tree before making a decision. Is this really faster? `compare` on numbers are at least in theory a single machine instruction!

**Comment by BlackCapCoder** [comment] 2022-11-19 04:16
This is equivalent to `ascend`, but `interval` is quite a bit quicker. 

```haskell
ascend2 = Bin 2 (Tip 1) (go 2#)
  where
    go n = Bin (I# x) (interval2 n) (go x)
      where x = n +# n

-- Creates the j'th left-subtree for ascend
interval2 j = go (iShiftRL# j 1#) j
  where
    go 0# _ = Z
    go n  i = Bin (I# x) (go n' i) (go n' x)
      where
        x  = n +# i
        n' = iShiftRL# n 1#
```

**Comment by meooow25** [comment] 2022-11-19 06:35
> What flags are you using when you run your benchmark?

`-O`

> Your version has to walk all the way to the bottom of the tree before making a decision? Is this really faster? 

I'm not sure what you're comparing against. If it's against the `Bin` approach then it is faster because the tree is never manifested as data, and it's not related `Bool` vs `Ordering`.

I think this is getting off-topic, so I'll address the main points and close this off.

- A binary tree approach
  Adds flexibility, but no examples of usefulness in competitive programming.
- `Bool` vs `Ordering`
  This is by design. On a range of integers, it simply finds the point of change of the `Bool`. I consider that being able to exit the search early on `EQ` is not worth the added complexity and friction at the call site.

**Closed by meooow25** 2022-11-19 06:35 UTC

**Comment by BlackCapCoder** [comment] 2022-11-19 07:02
Sorry for the spam, I'm basically just using this as an excuse to play with search trees :D

I might open a PR if I make it significant faster!
